[package]
name = "riscv-decoder"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = []

m = []
a = []
zicsr = ["zifencei"]
zifencei = []

s = ["zicsr"] # Supervisor

full = ["s", "a", "m", "zicsr", "zifencei"]

[dependencies]
thiserror = "2"