[package]
name = "riscv-decoder"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = []

m = []
a = []
zicsr = []
zifencei = []

s = ["zicsr"] # Supervisor

full = ["s", "m", "zicsr", "zifencei"]

[dependencies]
thiserror = "2"