[package]
name = "riscv-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
anyhow = "1"
crossterm = "0.29.0"
ratatui = {version = "0.30.0", features = ["crossterm"]}
riscv-core = {workspace = true}