[package]
name = "riscv-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
riscv-decoder = {workspace = true}

modular-bitfield = "0.13"

thiserror = "2"

[dev-dependencies]
riscv-loader = {workspace = true}
