[package]
name = "riscv-disasm"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
thiserror = "2"
riscv-loader = {workspace = true}
riscv-decoder = {workspace = true}