[package]
name = "riscv-disasm"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = []

m = ["riscv-decoder/m"]

[dependencies]
riscv-loader = {workspace = true}
riscv-decoder = {workspace = true}

thiserror = "2"
